// src/quality/avoid-css-conflict/vue/scoped-css/src/App.vue
<template>
  <div id="app">
    <div class="app">
      <a href="http://google.com">Google</a>
      <div class="text">Hello~</div>
      <div class="hi-you">Camel Word</div>

      <div class="rotate">旋转</div>

      <div class="ly ly-j p-20">
        <div>1</div>
        <div>1</div>
        <div>1</div>
      </div>
    </div>
  </div> 
</template>

// 全局CSS
<style src="@lucky-joel/css-utils"></style>
<style>
#app {
  background-color: #ddd;
}
</style>
// scoped css
<style scoped>
.text {
  text-align: center;
  color: green;
}

.hi-you {
  color: yellow;
}

.rotate {
  margin-top: 20px;
  display: inline-block;
  animation: rotate ease-in 3s infinite;
}

@keyframes rotate {
  0% {
    transform: rotate(0);
  }
  50% {
    transform: rotate(180deg);
  }

  100% {
    transform: rotate(360deg);
  }
}
</style>

// src/quality/avoid-css-conflict/react/css-modules/src/App.js
import React from 'react';
import s from './App.css';
import '@lucky-joel/css-utils'
import './util.global.css'

function App() {
  return (
    <div className="app">
      <a href="http://google.com">Google</a>
      <div className={s.text}>Hello~</div>
      <div className={s.hiYou}>Camel Word</div>

      <div className={s.rotate}>旋转</div>

      <div className="ly ly-j p-20">
        <div>1</div>
        <div>1</div>
        <div>1</div>
      </div>
    </div>
  );
}

export default App;
